spring:
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:testdb
#    schema: schema.sql
#    data: data.sql
    initialization-mode: always #never

  jpa:
    show-sql: true
    generate-ddl: false #true
    hibernate:
      ddl-auto: none #create
    properties:
      hibernate:
        format_sql: false
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  shell:
    interactive:
      enabled: true

logging:
  level:
    ROOT: ERROR