DROP TABLE IF EXISTS AUTHORS CASCADE;
DROP TABLE IF EXISTS GENRES CASCADE;
DROP TABLE IF EXISTS BOOKS CASCADE;
DROP TABLE IF EXISTS COMMENTS;
DROP TABLE IF EXISTS USERS;

CREATE TABLE AUTHORS(ID BIGSERIAL NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL UNIQUE);

CREATE TABLE GENRES(ID BIGSERIAL NOT NULL PRIMARY KEY, NAME VARCHAR(255) NOT NULL UNIQUE);

CREATE TABLE BOOKS(ID BIGSERIAL       NOT NULL PRIMARY KEY,
                   TITLE VARCHAR(255) NOT NULL UNIQUE,
                   AUTHOR_ID BIGINT   NOT NULL REFERENCES AUTHORS(ID),
                   GENRE_ID BIGINT    NOT NULL REFERENCES GENRES(ID)
                   );

 CREATE TABLE COMMENTS(ID BIGSERIAL NOT NULL PRIMARY KEY,
                      BOOK_ID BIGINT REFERENCES BOOKS(ID),
                      COMMENT VARCHAR(255) NOT NULL
                      );

CREATE TABLE USERS(
    ID BIGSERIAL NOT NULL PRIMARY KEY,
    NAME VARCHAR (255) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255),
    ROLE VARCHAR(255)
);