DROP TABLE IF EXISTS AUTHORS;
CREATE TABLE AUTHORS(ID BIGSERIAL PRIMARY KEY, NAME VARCHAR(255), SURNAME VARCHAR(255), PATRONYMIC VARCHAR(255));

DROP TABLE IF EXISTS GENRES;
CREATE TABLE GENRES(ID BIGSERIAL PRIMARY KEY, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(ID BIGSERIAL PRIMARY KEY, TITLE VARCHAR(255));

DROP TABLE IF EXISTS BOOKSTOAUTHORSTOGENRESLINK;
CREATE TABLE BOOKSTOAUTHORSTOGENRESLINK(ID BIGSERIAL PRIMARY KEY, BOOK_ID BIGINT, AUTHOR_ID BIGINT, GENRE_ID BIGINT);
