spring:
  messages:
    basename: i18n.messages
    fallback-to-system-locale: false
  datasource:
    url: jdbc:h2:mem:testdb
    schema: schema.sql
    data: data.sql
    initialization-mode: always
  h2:
    console:
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  shell:
    interactive:
      enabled: true